# Generated by Django 3.2.3 on 2021-05-23 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('url', models.URLField()),
                ('product_image_url', models.URLField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('saving', models.CharField(blank=True, max_length=100, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('price_difference', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('price_difference', '-created'),
            },
        ),
    ]
